# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mar Reguant
tagline:          'Mar Reguant's website'
description:      ''
url:              https://mreguant.github.io
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://mreguant.github.io

theme: jekyll-theme-minimal