# Dependencies
highlighter:      rouge

title:            Mar Reguant
tagline:          'Research page'
description:      'ICREA Researcher at CSIC-IAE and Professor at Northwestern University'
url:              https://mreguant.github.io
baseurl:          /

author:
  name:           'Mar Reguant'

paginate:         5
