# Dependencies
markdown:         redcarpet
highlighter:      pygments

title:            Mar Reguant
tagline:          'Research page'
description:      'Northwestern University, Department of Economics'
